services:
  influxdb:
    container_name: influxdb
    image: influxdb:2.7.7
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    networks:
      tig:
        aliases:
          - influxdb
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - 8086:8086

  telegraf:
    container_name: telegraf
    image: telegraf:1.31.1
    env_file:
      - .env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:rw
    networks:
      tig:
        aliases:
          - telegraf
    depends_on:
      - influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:11.0.1
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    networks:
      tig:
        aliases:
          - grafana
    env_file:
      - .env
    depends_on:
      - influxdb
    ports:
      - 3000:3000

volumes:
  grafana-storage:
    name: grafana-storage
  influxdb-storage:
    name: influxdb-storage


networks:
  tig:
    driver: bridge
    name: tig-network
